language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "No pull requests can be sent to the master branch" 1>&2;
      exit 1;
    fi

install:
  - pip install .
  - python setup.py install

script:
  - pytest