language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

sudo: false

install:
  - pip install .
  - pip install -r dev-requirements.txt

script:
  - pylint hesperidescli
  - tox

after_success:
    - coveralls
